api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'brand', views.CarBrandViewSet)
router.register(r'model', views.CarModelViewSet)
router.register(r'user-car', views.UserCarViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path("all/", views.list_all, name="all"),
    path("brand-create/", views.CarBrandCreateView.as_view(), name="brand_create"),
    path("brand/<int:pk>/update/",
         views.CarBrandUpdateView.as_view(), name='brand_update'),
    path("brand/<int:pk>/delete/",
         views.CarBrandDeleteView.as_view(), name='brand_delete'),
    path("model-create/", views.CarModelCreateView.as_view(), name="model_create"),
    path("model/<int:pk>/update/",
         views.CarModelUpdateView.as_view(), name='model_update'),
    path("model/<int:pk>/delete/",
         views.CarModelDeleteView.as_view(), name='model_delete'),
    path("user-car-create/", views.UserCarCreateView.as_view(),
         name="user_car_create"),
    path("user-car/<int:pk>/update/",
         views.UserCarUpdateView.as_view(), name='user_car_update'),
    path("user-car/<int:pk>/delete/",
         views.UserCarDeleteView.as_view(), name='user_car_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cars/", include("cars.urls")),
    path("accounts/", include("accounts.urls")),
    path("api/", include("api.urls")),
]

cars/models.py
from django.db import models
from accounts.models import CustomUser

from common.soft_delete import SoftDeleteModel

class CarBrand(SoftDeleteModel):
    name = models.CharField(max_length=120, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class CarModel(SoftDeleteModel):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


class UserCar(SoftDeleteModel):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    car_model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    first_reg = models.DateField(null=True)
    odometer = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.car_brand} {self.car_model}"

cars/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import CarBrand, CarModel, UserCar


def list_all(request):
    brands = CarBrand.objects.all()
    models = CarModel.objects.all()
    user_cars = UserCar.objects.all()
    return render(request, 'cars/list.html', {'brands': brands, 'models': models, 'user_cars': user_cars})


class CarBrandCreateView(CreateView):
    model = CarBrand
    fields = ('name',)
    template_name = 'cars/create.html'
    success_url = reverse_lazy('cars:all')


class CarBrandUpdateView(UpdateView):
    model = CarBrand
    fields = ('name',)
    template_name = 'cars/create.html'
    success_url = reverse_lazy('cars:all')


class CarBrandDeleteView(DeleteView):
    model = CarBrand
    template_name = 'cars/delete.html'
    success_url = reverse_lazy('cars:all')


class CarModelCreateView(CreateView):
    model = CarModel
    fields = ('car_brand', 'name',)
    template_name = 'cars/create.html'
    success_url = reverse_lazy('cars:all')


class CarModelUpdateView(UpdateView):
    model = CarModel
    fields = ('car_brand', 'name',)
    template_name = 'cars/create.html'
    success_url = reverse_lazy('cars:all')


class CarModelDeleteView(DeleteView):
    model = CarModel
    template_name = 'cars/delete.html'
    success_url = reverse_lazy('cars:all')


class UserCarCreateView(CreateView):
    model = UserCar
    fields = ('user', 'car_brand', 'car_model', 'first_reg', 'odometer',)
    template_name = 'cars/create.html'
    success_url = reverse_lazy('cars:all')


class UserCarUpdateView(UpdateView):
    model = UserCar
    fields = ('user', 'car_brand', 'car_model', 'first_reg', 'odometer',)
    template_name = 'cars/create.html'
    success_url = reverse_lazy('cars:all')


class UserCarDeleteView(DeleteView):
    model = UserCar
    template_name = 'cars/delete.html'
    success_url = reverse_lazy('cars:all')

cars/templates/cars/create.html
{% extends "base.html" %}

    {% block content %}
        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_p }}
            </table>
            <input type="submit" value="Submit">
            <input type="button" value="Cancel" onclick="history.back()">
        </form>
    {% endblock %}

cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
    <p>Are you sure you want to delete {{ object }} ?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes.">
    </form>
{% endblock %}

cars/templates/cars/list.html
{% extends "base.html" %}

    {% block content %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
        <h1>Car Brands</h1>
            {% for brand in brands %}
                {{ brand }}
                <a href="{% url 'cars:brand_update' brand.pk %}">Edit</a>
                <a href="{% url 'cars:brand_delete' brand.pk %}">Delete</a>
                <br>
            {% endfor %}
        <h1>Car Models</h1>
            {% for model in models %}
                {{ model }}
                <a href="{% url 'cars:model_update' model.pk %}">Edit</a>
                <a href="{% url 'cars:model_delete' model.pk %}">Delete</a>
                <br>
            {% endfor %}
        <h1>User Cars</h1>
            {% for user_car in user_cars %}
                {{ user_car }}
                {% if request.user.is_authenticated and request.user == user_car.user %}
                    <a href="{% url 'cars:user_car_update' user_car.pk %}">Edit</a>
                    <a href="{% url 'cars:user_car_delete' user_car.pk %}">Delete</a>
                {% endif %}
                <br>
            {% endfor %}
    {% endblock %}